[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

# Environment variables are set in Netlify dashboard, not here
# ELEVENLABS_API_KEY - Set in Netlify UI
# ELEVENLABS_VOICE_ID - Set in Netlify UI